[package]
edition = "2021"
name = "review_contract"
version = "1.1.0"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
candid = "0.10"
ic-cdk = "0.12"
serde = { version = "1.0", features = ["derive"] }
ic-cdk-macros = "0.8"